stages:
  - build
  - cross

cache:
  key: "$CI_BUILD_REF"
  untracked: true
  paths:
  - sandscript-library-interface/*
  - sandscript-map-extension.so

rpm:
  tags:
  - centos_build:7
  stage: build
  script:
  - echo "Started at $(date -Iseconds)"
  - rm -rf sandscript-library-interface
  - make clean
  - make
  - make rpm-release

  artifacts:
    paths:
    - sandscript-map-extension*.rpm

freebsd:
  tags:
  - freebsd-build
  stage: cross
  script:
  - make
  - mkdir -p /tmp/freebsd-pkg/lib /tmp/freebsd-pkg/sandvine/loadable
  - cp -f sandscript-map-extension.so /tmp/freebsd-pkg/sandvine/loadable/sandscript-map-extension.so
  - cp -f freebsd-pkg/* /tmp/freebsd-pkg
  - sed -i -e "s?VERSION?$(cat VERSION)?" /tmp/freebsd-pkg/+CONTENTS
  - rm -f sandscript-map-extension-$(cat VERSION).tar sandscript-map-extension-$(cat VERSION).bz2
  - (P=$(pwd); cd /tmp/freebsd-pkg; tar cf $P/sandscript-map-extension-$(cat $P/VERSION).tar .)
  - bzip2 -c sandscript-map-extension-$(cat VERSION).tar > sandscript-map-extension-$(cat VERSION).bz2
  artifacts:
    paths:
    - sandscript-map-extension*bz2
  artifacts:
    paths:
    - sandscript-map-extension*bz2

